### ISSUE TITLE
Events on Image Manipulation

### ISSUE THREAD

**Issue by maxm74** [bgrabitmap/bgracontrols#103]
I going to use this Control on a Project and I noticed that there is no Events to interact with Crop Areas and with the Control in general.
I made a Fork, I'll send you the changes shortly (if you are interested).

**Comment by lainz** [comment]
Yes thanks. Feel free to make a pull request and a small demo we can include.

**Comment by maxm74** [comment]
Done first steps. I made a Pull request, demo will coming soon. Thanks

**Comment by maxm74** [comment]
Hi, i made a lot of changes in Imagemanipulation. When I finish doing all
the tests I will make a new pull request. If in the meantime you accept the
one I have already done it only contains the events. Thank you.

Il Lun 1 Mar 2021, 16:56 Leandro Diaz ***@***.***> ha scritto:

**Comment by lainz** [comment]
Hi. Yes I didn't have time to test it. Also we add new stuff in the
dev-bgracontrols branch. The master is only for releases. So if you can in
the next pull request use the dev branch.
