### ISSUE TITLE
BGRAFlashProgressBar Positon?

### ISSUE THREAD

**Issue by qwer0123456** [bgrabitmap/bgracontrols#106]
<img width="911" alt="nomal" src="https://user-images.githubusercontent.com/80979849/113469682-8c967380-948a-11eb-9322-8d012db620a2.png">

<img width="1165" alt="bgra" src="https://user-images.githubusercontent.com/80979849/113469685-8f916400-948a-11eb-8f89-28a964f4f995.png">

BGRAFlashProgressBar does not have a Position function

Same function as Position in BGRAFlashProgressBar

Is there a function to do?

**Comment by circular17** [comment]
The property is called Value.

**Comment by qwer0123456** [comment]
> The property is called Value.

thank you
