### ISSUE TITLE
bcpaperlistbox.rc

### ISSUE THREAD

**Issue by ak545** [bgrabitmap/bgracontrols#12]
Hello!

When you compile bclistbox.pas under Linux, an error occurs:
Error: resource compiler "windres.exe" not found, switching to external mode
This is because Linux does not have any .exe...
I avoided this problem in this way:
Compiled the package in the Windows environment. I got the file ..\bgracontrols-master\lib\x86_64-win64\3.0.2\bcpaperlistbox.res which I then copied into the ..\bgracontrols-master\bcpaperlistbox.res and in the file ..\bgracontrols-master\bclistbox.pas replaced {$R bcpaperlistbox.rc} to {$R bcpaperlistbox.res}

I think this is better to fix via {$I bcpaperlistbox.lrs}

Lazarus 1.6.4 Win64/Linux Fedora 25 64-bit

Thanks!

**Comment by lainz** [comment]
Hi, you can do a pull request with the {$I bcpaperlistbox.lrs}, because I can't get it working. And I'm not sure if using a .res is a good way to solve it.

**Comment by ak545** [comment]
for bcpaperlistbox.lrs ...
For this you need to rewrite part of the code. It is better to address this question to the author.

**Comment by lainz** [comment]
I'm the author. But never used .lrs outside the register function, I thought maybe you know the solution. Well seems that I need to ask in the forum if someone else knows how to do it.

**Comment by ak545** [comment]
Unfortunately, I do not know. Sorry.

**Comment by ak545** [comment]
http://wiki.freepascal.org/How_To_Write_Lazarus_Component
Step 3: Create icons for the package 
?

**Comment by lainz** [comment]
Thanks for your help I will try to fix it soon.

**Comment by ak545** [comment]
I wish you success!
;)

**Comment by lainz** [comment]
Fixed, please test.

**Comment by ak545** [comment]
Hi! 

Under Windows successfully.
Under Linux I will check on Monday and let you know.

Thanks!
;)

**Comment by ak545** [comment]
Although, why wait for Monday?
Under Linux is also successful.
Thanks a lot!
