### ISSUE TITLE
Set the color of svg icons in the PopulateImageList method

### ISSUE THREAD

**Issue by SSinteZ** [bgrabitmap/bgracontrols#123]
There is no way to set the color of svg icons in the PopulateImageList method. Useful for creating light and dark app theme

**Comment by lainz** [comment]
Hi, is not that easy I think, at least you must iterate each color in the XML of the svg image, and apply a function into it to make it darker or lighter.

**Comment by circular17** [comment]
I can see 3 ways to do it:
- iterate through the XML
- iterate through the SVG elements (I've just added an IterateElements method to do that). Here is a sample callback function:
```pascal
procedure TForm1.ChangeFill(AElement: TSVGElement; AData: pointer;
  var ARecursive: boolean);
begin
  if AElement is TSVGDefine then
    ARecursive:= false
  else
  begin
   if not AElement.isFillNone then AElement.fillColor := CSSSkyBlue;
   if not AElement.isStrokeNone then AElement.strokeColor := CSSOrange;
  end;
end; 

// used like this:
svg.IterateElements(@ChangeFill, nil, true);
```

- to use the currentColor variable in the SVG and to define it at the top level when drawing the SVG (I've just added a Color property to TBGRASVG class)
- render the SVG in a temporary image and apply a filter to change its color (as done in TBGRASVGTheme)
