### ISSUE TITLE
[7.5] Cannot compile package with FPC 3.0.4

### ISSUE THREAD

**Issue by StarWolf3000** [bgrabitmap/bgracontrols#129]
I'm using Lazarus 2.0.8 with FPC 3.0.4, and I tried to update BGRAControls to 7.5.0.0, but the compiler fails at:
`onlinepackagemanager\packages\bgracontrols-master\bgrasvgimagelist.pas(266,11) Error: identifier idents no member "ForceQueue"`

This is the procedure in question:
```pascal
procedure TBGRASVGImageList.QueryRasterize;
var method: TThreadMethod;
begin
  FRasterized := false;
  method := RasterizeIfNeeded;
  TThread.ForceQueue(nil, method);
end;
```

The scripting components package compiled without any issues.

I wanted to update all packages before updating Lazarus and FPC.

**Comment by lainz** [comment]
Hi. Try updating to latest Lazarus and FPC.

**Comment by StarWolf3000** [comment]
After updating to FPC 3.2.2 and Lazarus 2.2.2, it worked without problems. I've been using the version from OPM, where it states that it is compatible with FPC 3.0.4, which after my experience is not the case. Checking out some posts on the Lazarus forum gave me intel that `ForceQueue` was added in a revision after 3.0.4.

**Comment by circular17** [comment]
Would be interesting to know if there is an alternative to ForceQueue, for compatibility with older LCL

**Comment by lainz** [comment]
Basically it adds to next ProcessMessages the call to the function?

There is Application.QueueAsyncCall, but I'm not sure if it's the same..

**Comment by circular17** [comment]
Yes that's the idea.

It seems to be the same basically.

**Comment by lainz** [comment]
Ok I will talk in the OPM thread to advice that doesn't work anymore with
3.0.4.
