### ISSUE TITLE
Close problem with Lazarus 1.6.4

### ISSUE THREAD

**Issue by GitHubStefan13** [bgrabitmap/bgracontrols#13]
![example](https://cloud.githubusercontent.com/assets/22775528/25276440/8545acac-269a-11e7-9aa7-af02d836002b.png)

When you put the Interfaces after the Unit-Forms bgacontrols will cause a crash after you close the Programm(as seen in Picture)

Don't know if this is a problem with your Controls or Lazarus itself. Still thought its worth mentioning, 
since i had no clue what caused the Problem. 

Putting the Interface before the Unit-Form solves it though.

**Comment by lainz** [comment]
Hi, I can confirm that but I'm not sure if I understand why it happens. Well at least you found a way to solve it.

**Comment by GitHubStefan13** [comment]
My theory is that Larazus destroys the Objects in the Order of the uses.
So first it destroys the Button in the Form-Unit after succesfully destroying it the object doesnt exist anymore but somehow Lazarus tries to destroy the Button in the Interface Unit again, thus the Access Violation on a non existing Object.

**Comment by lainz** [comment]
Ok. I will close it as we can do nothing to solve this.
