### ISSUE TITLE
Rounding corners feature is not working on Windows

### ISSUE THREAD

**Issue by KodeZwerg** [bgrabitmap/bgracontrols#136]
Rounding corners feature is not working on Windows
As you asked here
https://forum.lazarus.freepascal.org/index.php/topic,62417.msg472005.html#msg472005
I put this up
Tested with v7.6.0.0 on 64bit Windows 10 using BCLabel component

**Comment by lainz** [comment]
Iw working fine, the thing is the set of options required to work. I will comment that in the forum.

**Comment by KodeZwerg** [comment]
Your last explanation was letting me see my error
https://forum.lazarus.freepascal.org/index.php/topic,62417.msg472067.html#msg472067
The error was behind the keyboard - Me!
Thank you so much for your assistance and your wonderful components!!

-Issue Closed
