### ISSUE TITLE
Compiling on linux mint with Lazarus 1.8.0RC3

### ISSUE THREAD

**Issue by mehmetulukaya** [bgrabitmap/bgracontrols#14]
Hello,

I am trying to compile bgracontrols or bgrabitmaps into lazarus 1.8.0rc3.
But compiler giving some error messages:

İletiler, Warnings: 1
Warning: other sources path of package "lnetbase 0.6.6" contains directory "../lib", which is already in the unit search path.
Build IDE: Exit code 512, Errors: 1
[lazarus] Error 1
[idepkg] Error 2
make: *** [idepkg] Error 2
lazarus.pp(161,1) Error: Error while linking

So I also installed windres for linux with by "sudo apt-get install mingw32" but I couldn't success.

What should I do for installing?

**Comment by lainz** [comment]
Please ask in the Lazarus forum, I don't have linux to test.
