### ISSUE TITLE
ribbon - increasing memory size after resize

### ISSUE THREAD

**Issue by velissariouc** [bgrabitmap/bgracontrols#15]
hi,
I have compiled bgracontrols-master\test\BGRA Ribbon Custom\BGRARibbon and run it on windows 10.
Every time I resize the application, I see in taskmanager that the memory size increases.

**Comment by lainz** [comment]
Thanks for reporting it. I've fixed it.
https://github.com/bgrabitmap/bgracontrols/commit/11a24a03b86ec43ae7b40815a24073734a144517

**Comment by mariokas** [comment]
Despues de compilar los primeros genera este error: 

Compile package bgracontrols 6.0.4: Exit code 1, Errors: 3
bcnumerickeyboard.pas(129,34) Error: Variable identifier expected
bcnumerickeyboard.pas(143,34) Error: Variable identifier expected
bcnumerickeyboard.pas(157,34) Error: Variable identifier expected

How can you fix it?

**Comment by circular17** [comment]
Hmmm it seems it is not the same topic.
Not sure but it seems to be related to the @ sign.
