### ISSUE TITLE
Tbgrathemesurface class inherited from

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#152]
Hi @circular17 is possible to inherit this class from TWinControl instead of Custom Control.

For example in Lazarus there is TCheckListBox and I can't use Tbgrathemesurface on its custom drawing.

**Comment by circular17** [comment]
Hi Lainz. I am not sure it is possible because TBGRAThemeSurface accesses the Canvas property of the control and TWinControl doesn't have this property.

**Comment by lainz** [comment]
Hi yes it has a canvas. Sure an alternative constructor can do.

**Comment by lainz** [comment]
Thank you I will try.

**Comment by lainz** [comment]
Done. Seems that works fine.
But I don't have macOS retina to test, can you give a try, the demo is in bgracontrols\test\test_checklistbox

**Comment by circular17** [comment]
Cool! I've checked it out and it works well.

I've made some adjustments by adding a scale factor and some margin. On MacOS, there's a frame rectangle that inverts the color and it was masking the square of the checkbox. With these changes, it looks good now.

Could you pull the latest and check on your end as well? Let me know if you have any further concerns.

**Comment by lainz** [comment]
Working well, thankyou!
Now we have another working demo =)
