### ISSUE TITLE
TBCPanel always disable ParentBackground

### ISSUE THREAD

**Issue by cbeier-studio** [bgrabitmap/bgracontrols#154]
When reopening a form that has TBCPanel, it always sets its ParentBackground to False. It is not an issue most of the time.

But when the TBCPanel is a child of another TBCPanel, BorderBCStyle is bpsBorder, and Rounding is used (RoundX, RoundY greater than 1), then it gets the background color of the parent TBCPanel's parent and paints it in the corners. Setting the ParentBackground to True, solves the issue. But when the form is reopened it sets back to False, and it gets a bit annoying when using various TBCPanel in various forms.

I am using Lazarus 3.0RC1, FPC 3.2.2 on Windows 11. BGRAControls package version is 7.7.

![Captura de tela 2023-10-13 105456](https://github.com/bgrabitmap/bgracontrols/assets/109050697/4b102508-0972-41af-8f5d-034134dab909)

**Comment by lainz** [comment]
Hi. I understand. I will try to fix it

**Comment by lainz** [comment]
Hi sorry I can't fix it. I'm not sure who added that code but only works in trunk apparently... I have only current release. The code is grayed on my editor. 

@maxm74 @circular17 maybe one of the two has an idea about it? I'm lost.

**Comment by circular17** [comment]
Hi!

I am not sure what happens or what "form is reopened" means. Is it that when the form is created, it has the wanted behavior and when it is hidden and shown again, this changes? I suppose that `ParentBackground = False` means that the component is opaque and so the background color is from the `Color` property. One way could be to set this color to be the wanted one.

Regards

**Comment by lainz** [comment]
Hi. Thanks for your response.

About setting the color. We should publish the Color property?

**Comment by lainz** [comment]
Hi, I've added Color property. That solves the issue.

![Captura de pantalla 2023-10-14 062801](https://github.com/bgrabitmap/bgracontrols/assets/4131395/23a90544-23e7-49d3-ad9a-24b80c892796)

**Comment by cbeier-studio** [comment]
Hi, thank you for the answers! 

> Hi, I've added Color property. That solves the issue.
Nice! It solves my issue. Thanks!
