### ISSUE TITLE
BGRASVGIMageList memory leak

### ISSUE THREAD

**Issue by a-wissing** [bgrabitmap/bgracontrols#156]
It seems that there is a problem with the BGRASVGImageList component:

![BGRA_SVGImageList_Issue](https://github.com/bgrabitmap/bgracontrols/assets/29145380/72ba3920-cdfe-41f4-b41e-9ba403689bdd)

Create new(empty) project.
Drag BGRAImageList onto the form.

Tested with Lazarus 2.2.6 and 3.0RC2
both with the packages from the online package manager and installed from the master trunk.

The problem could also be reproduced with the test program "test_svg_theme".

**Comment by a-wissing** [comment]
additional Info: Tested on Windows 10/11 only

**Comment by lainz** [comment]
Hi. It's a problem of XML of Lazarus. It's fixed in trunk.
Use Lazarus trunk and try.
