### ISSUE TITLE
Got a question...TBCButton in control

### ISSUE THREAD

**Issue by AlfonsoMartitegui** [bgrabitmap/bgracontrols#16]
Im using a TBCButton in a component.
Everything works fine, but if I wanna assignstyle using AssignFromFile i goes to hell everything.
dont know if ist because the path. but i check that
exist:=FileExists('../styles/google-menu.bcbtn') //Exists is true
and then:
buton_1.AssignFromFile('../styles/google-menu.bcbtn');
and Its so awfull that IDE hangs and closes.
Is there something im missing?
regards

**Comment by lainz** [comment]
Hi, bcbtn files are for IDE only.
