### ISSUE TITLE
unitbgraimagemanipulationdemo.pas does not compile

### ISSUE THREAD

**Issue by KoBraSoft** [bgrabitmap/bgracontrols#164]
I am trying to compile unitbgraimagemanipulationdemo.pas from dev-bgracontrols and I get this error messages:

    unitbgraimagemanipulationdemo.pas(574,78) Error: Incompatible type for arg no. 1: Got "TRect", expected "TRectF"
    bgraimagemanipulation.pas(3303,33) Hint: Found declaration: addCropArea(TRectF;TResolutionUnit=`0`;LongInt=`-1`):TCropArea;
    unitbgraimagemanipulationdemo.pas(575,72) Error: Incompatible type for arg no. 1: Got "TRect", expected "TRectF"
    bgraimagemanipulation.pas(3303,33) Hint: Found declaration: addCropArea(TRectF;TResolutionUnit=`0`;LongInt=`-1`):TCropArea;

**Comment by lainz** [comment]
@maxm74 hi, please check if it compiles with current release of FPC and Lazarus, not just in trunk...

**Comment by maxm74** [comment]
simply used RectF() intestead of Rect()

**Comment by lainz** [comment]
Thankyou =)
