### ISSUE TITLE
Failure to compile BGRABitmap with FPC 3.3.1

### ISSUE THREAD

**Issue by wp-xyz** [bgrabitmap/bgracontrols#166]
In a recent change of FPC the visibility of declarations in classes (private, protected, public, published) is pursued more strictly. As a consequence, the package bgrabitmappack.lpk does not compile any more: "bgrasvgtype.pas(501,19) Error: Identifier not found "PT"" (maybe there are more of this type). The compilation aborts because PT is a private field in TFPGList declared in a different unit from where it is accessed.

**Comment by circular17** [comment]
Handled in BGRABitmap project: https://github.com/bgrabitmap/bgrabitmap/issues/237
