### ISSUE TITLE
Hi Lainz...SO there is no way to assignstyle...

### ISSUE THREAD

**Issue by AlfonsoMartitegui** [bgrabitmap/bgracontrols#17]
Hi LAinz,
First of all, even if not said anything before.., the package is awesome. Great loocking.

One last question, please. 
There is no way to load a style if not in graphical mode in IDE.
I mean, i wanna use a  TBCButton within a component so no graphical interface.
Something like:

buton_1:=TBCButton.create(self);
buton_1.Parent:=self;
buton_1.Width:=25;
buton_1.ShowCaption:=false;
buton_1.DropDownArrowSize:=18;
buton_1.DropDownWidth:=25;
buton_1.DropDownArrow:=true;  

.....
But cant find how to assign style....
Hope can gimme a tip on in.

Regards

**Comment by lainz** [comment]
Hi, you can first style a button with the IDE in a separate project for example, and then run it with a BCButton1.SaveToFile... that file you can use in any project with BCButton1.LoadFromFile... or BCButton1.AssignFromFile...

```
{ Save all published settings to file }
procedure SaveToFile(AFileName: string);
{ Load and assign all published settings from file }
procedure LoadFromFile(AFileName: string);
{ Assign the properties from AFileName to this instance }
procedure AssignFromFile(AFileName: string);
```

The one you should use is AssignFromFile.

**Comment by AlfonsoMartitegui** [comment]
Lainz... WORKS like a cham. Great job dude.
And just a little question and I wont bother you again... well two questions really.
1- To create a new style can I just copy all text data in the bcbtn file and modify (some color for example) and save it (not changin name ... ) open it and do the save file and assign from file..??
2- well it depends on question 1. I guess there is no graphical editor made for button. but if it works question 1 i can arrange to build one. so firs question is the important on.

Again .. great tool

**Comment by lainz** [comment]
1) Try it, I never did that, but they are almost the same format.
Try this: save a new file with SaveToFile and edit that file with the contents of the bcbtn with a text editor, keeping the format (naming of variables).
2) The only graphical editor is the Object Inspector. But you can easily build one, in fact I've build one long time ago in no time, but I don't have the sources right now.
