### ISSUE TITLE
Forgetting to set a PopupMenu causes runtime exception

### ISSUE THREAD

**Issue by sganz** [bgrabitmap/bgracontrols#171]
Submitted a small pull request.

In ColorSpeedButton.pas:560

```
  if PopupMode then
  begin
    p := Parent.ClientToScreen(Point(Left, Top));
    PopupMenu.PopUp(p.x, p.y + Height);
  end;
```
If you forget to set the PopupMenu property after settintg the PopupMode to True, you can have a runtime exception.

This is in this [Pull Request](https://github.com/bgrabitmap/bgracontrols/pulls)

**Comment by lainz** [comment]
Applied pull request. Thanks.
