### ISSUE TITLE
BGRAImageManipulation dividing by zero

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgracontrols#189]
Create new project and drop BGRAImageManipulation on the form and run. Dividing by zero error will be shown. Also check provided example for it as it can't compile and doesn't work well even with loaded jpg image when problematic code is removed from demo (ReadWriteConfig or similar).

See [forum thread](https://forum.lazarus.freepascal.org/index.php/topic,68159.0.html)

**Comment by maxm74** [comment]
Solved

**Comment by circular17** [comment]
Thank you very much indeed
