### ISSUE TITLE
Unable to rebuild IDE with bgracontrols on Linux

### ISSUE THREAD

**Issue by ClaudeMa** [bgrabitmap/bgracontrols#19]
Unable to rebuild IDE with  BragControls on Linux 
Debian 8 32 bits, Debian 9 x64 and Fedora 27 x64

Lazarus 1.8.0
FPC 3.0.4
from sourceforges
All other packages build fine but trying  to install bgracontrols building IDE fail with

> [Makefile:3961: lazarus] Error 1
> [Makefile:4383: idepkg] Error 2
> make: *** [Makefile:3261: idepkg] Error 2
> lazarus.pp(161,1) Error: Error while linking

No other error are displayed. 
After that, removing package bgracontrols in package manager and trying to build IDE always fail
i must remove .lazarus in my home folder and loose all package to rebuild IDE

**Comment by lainz** [comment]
Hi. Please install all dependency listed in readme.md

**Comment by lainz** [comment]
libxtst-dev and libgl-dev

**Comment by lainz** [comment]
Hi. Please see the readme file in the repository and install the system
dependencies.
