### ISSUE TITLE
BGRAVirtualscreen z-order

### ISSUE THREAD

**Issue by MaartenJB** [bgrabitmap/bgracontrols#33]
Hi,

I've got a problem with the BGRAVirtualscreen.  I cant change the z-order to move it to the back. It is always on top of other components, for example the TBCButton.  

Reproduce:
Place a TBCButton and a BGRAVirtualscreen on the form, and try to send the virtual screen to the back so that the button is visible when you drag it over the virtual screen. (I don't want the virtual screen to be the parent of the button)

I use the github master version of bgracontrols/bgrabitmap and use Lazarus 1.8.0

Best regards,

Maarten

**Comment by lainz** [comment]
Hi, that is not possible. Instead of a virtualscreen use a
TBCGraphicControl that can be painted as well.

**Comment by MaartenJB** [comment]
ok, thanks, is this just as fast as the virtual screen?

**Comment by lainz** [comment]
Yes is the same just that its like a paintbox, the virtualscreen is like a
panel.

**Comment by MaartenJB** [comment]
ok thank you!
