### ISSUE TITLE
BCButton cut off in groupbox

### ISSUE THREAD

**Issue by Tesla2k** [bgrabitmap/bgracontrols#44]
Hello,
when I place a TBCButton inside a TGroupBox the Button is cut of at the top. This problem only occurse when I compile my project for my raspberry pi. On Windows everything looks ok.

Example of the problem:

![grafik](https://user-images.githubusercontent.com/9998533/56810417-8cb97d80-6836-11e9-8c26-6589df453f34.png)

**Comment by lainz** [comment]
Try with BCButtonFocus, to see if the bug is there too.

**Comment by lainz** [comment]
No feedback, we can't do nothing, can be LCL bug or BGRA bug, but we don't have hardware to test.

**Comment by Tesla2k** [comment]
Sorry for the long delay. With BCButtonFocus the problem does not occur

![grafik](https://user-images.githubusercontent.com/9998533/61058854-49fc5000-a3f8-11e9-992d-9d6aa9c3a603.png)

**Comment by circular17** [comment]
That's surprising.

This may be related to the client area of the GroupBox1. If you put a regular label for example, is it as well cut off?

**Comment by lainz** [comment]
Indeed. For example what happens if you put a label or a SpeedButton that are descendants of TGraphicControl.
