### ISSUE TITLE
Exception with newest BGRABitmap

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#46]
There is an exception with TBGRABitmapEx bcbasectrls.pas, I can reproduce this sometimes in a form that uses a lot of BCButton.

#0 BGRADEFAULTBITMAP$_$TBGRADEFAULTBITMAP_$__$$_DOALPHACORRECTION at :0
#1 BGRAWINBITMAP$_$TBGRAWINBITMAP_$__$$_LOADFROMBITMAPIFNEEDED at :0
#2 BGRABITMAPTYPES$_$TCUSTOMUNIVERSALBITMAP_$__$$_FILL$TUNIVERSALBRUSH$WORD at :0
#3 BGRABITMAPTYPES$_$TGENERICUNIVERSALBITMAP$2$CRC2743D80F_$__$$_FILL$TBGRAPIXEL at :0
#4 BCBUTTON$_$TCUSTOMBCBUTTON_$__$$_RENDER$TBGRABITMAPEX$TBCBUTTONSTATE at :0
#5 BCBUTTON$_$TCUSTOMBCBUTTON_$__$$_DRAWCONTROL at :0
#6 BCBASECTRLS$_$TBCGRAPHICCONTROL_$__$$_PAINT at :0
#7 CONTROLS$_$TGRAPHICCONTROL_$__$$_WMPAINT$TLMPAINT at :0
#8 SYSTEM$_$TOBJECT_$__$$_DISPATCH$formal at :0
#9 ?? at :0
#10 VMT_$CONTROLS_$$_TWINCONTROLENUMERATOR$indirect at :0
#11 CONTROLS$_$TGRAPHICCONTROL_$__$$_DESTROY at :0

I will try to reproduce making a demo that shows the bug.

**Comment by circular17** [comment]
Hmmm maybe the BCButton tries to draw itself after being destroyed?

**Comment by circular17** [comment]
By the way what is the error?

**Comment by circular17** [comment]
Note : I just fixed something with alpha correction so I suggest you pull the last version, though I don't think it will change something.

**Comment by lainz** [comment]
Seems that the error is on the first paint, the buttons are inside a TPanel, when showing the form the buttons area is white, until I close the error message.
![bcbuttonerror](https://user-images.githubusercontent.com/4131395/60385075-c0459d80-9a5b-11e9-8407-707177a35713.png)

**Comment by lainz** [comment]
If I change the color of the button to clBtnFace instead of clNone this shows:
![bcbuttonerror2](https://user-images.githubusercontent.com/4131395/60385439-78c11080-9a5f-11e9-87e9-a5844063ed78.png)

**Comment by lainz** [comment]
This error is shown the second time the form is shown to the user, seems that the Bitmap in memory is deleted, since the buttons don't show up. I will try again to replicate to see if I can attach a program, for now I can only replicate on the application.

**Comment by lainz** [comment]
I fixed this this way:

```Pascal
{ Set the size of the current bitmap. All data is lost during the process }
procedure TBGRADefaultBitmap.SetSize(AWidth, AHeight: integer);
begin
  inherited SetSize(AWidth, AHeight);
  //FreeBitmap;
end;  
```

in file BGRADefaultBitmap, commenting FreeBitmap, it works but I'm not sure, what do you think?

**Comment by circular17** [comment]
I think it makes sense to free the Bitmap at this point. It is recreated if necessary.

What line raises the exception?

**Comment by circular17** [comment]
It seems that lines do not show up in the stack trace. Maybe there are still optimizations on?

**Comment by lainz** [comment]
Let me see

**Comment by lainz** [comment]
Here are all the lines, bgracontrols and bgrabitmap
![callstack](https://user-images.githubusercontent.com/4131395/60386241-fb020280-9a68-11e9-8147-7e71bb24028d.png)

**Comment by lainz** [comment]
![line](https://user-images.githubusercontent.com/4131395/60386314-aad77000-9a69-11e9-8168-30b2b1f52b12.png)

**Comment by circular17** [comment]
I see. I suppose FDataByte = nil? What about NbPixels?

**Comment by circular17** [comment]
Does it solve to add a test?
`if CanvasAlphaCorrection and (FDataByte<>nil) then`

**Comment by lainz** [comment]
N is 1599
FDataByte can not access memory at address

**Comment by lainz** [comment]
I will check your code, let me see

**Comment by circular17** [comment]
Ok so NbPixels is not set correctly? If Width = 0 and Height = 0, then NbPixels would be 0

**Comment by lainz** [comment]
I added writeln(Width) and also for height, and both display 40.

**Comment by lainz** [comment]
FDataByte is not nill, because it enters to the same line of the exception

**Comment by circular17** [comment]
Ok so it is normal the it goes through the loop. That does not seem related to SetSize(0,0) then because the size is not zero.

I realized that because of automatic conversions between colors, there is another change to make. The highlighted line should be:
`      if (plongword(p)^ and colormask <> 0) and (p^.alpha = 0) then`
that is plongword(p)^ instead of longword(p^)

Though I doubt that it would cause an access violation.

**Comment by lainz** [comment]
Changing that line produces the same exception.

**Comment by circular17** [comment]
I don't know. :-( 

Maybe I can find if you send me your sample project?

**Comment by lainz** [comment]
Sure, is in an application that's not mine, but I will try to replicate, else ask permission to send you the application.

**Comment by lainz** [comment]
Well, this was a fault in the code of the form. But it was working with old bgrabitmap, and not with the newest. Maybe a combination we can't detect. Even I copy the entire form to send it to you and the bug didn't appear in a plain form without code.

The fault was that there is a panel container, and is not visible by default, seems that there is a change in the captions of the buttons, and that triggers the refresh, then try to paint but there is no panel visible to paint the button into. Then it crash. Maybe is a bug in trunk LCL, plus some change in bgra that we can't find.

Anyways, I fixed the problematic form, and you can safely release BGRABitmap now. We know if someone has this problem is because container not visible and triggering a repaint.

**Comment by circular17** [comment]
Ok. That’s kind of mysterious
