### ISSUE TITLE
RT_RCDATA

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#53]
bcimagebutton.pas(1393,45) Warning: Symbol "RT_RCDATA" is deprecated: "Use Windows.RT_RCDATA instead"

@circular17 you fixed something similar for BGRABitmap right? How it can be fixed for BGRAControls?

**Comment by circular17** [comment]
Well I suppose you can solve it by writing {$ifdef Windows}Windows.{$endif} before the constant RT_*

**Comment by lainz** [comment]
Ok thanks.
