### ISSUE TITLE
bgra checkbox add?

### ISSUE THREAD

**Issue by kitty8904** [bgrabitmap/bgracontrols#56]
<img width="742" alt="55" src="https://user-images.githubusercontent.com/18622105/70381895-a0fd5580-1995-11ea-8e60-1f10745df4cb.png">

Is there a BGRA-only check box button?

**Comment by lainz** [comment]
Hi. There is a toggle state for bcimagebutton. There is checkbox mode for
bcmaterialdesignbutton. There is a checkbox control in bgrathemes tab (and
is bgra only doesn't require custom drawn package).

**Comment by kitty8904** [comment]
<img width="531" alt="555" src="https://user-images.githubusercontent.com/18622105/70383041-6b169c00-19aa-11ea-9449-cd48e9de282b.png">

thank you BGRA themes Checkbox found

but bcmaterialdesignbutton checkbox mode??

**Comment by lainz** [comment]
Hi yes you're  right.

The control is BCMDButton and the property is "Kind" mdbkCheckBox or
mdbkToggle. There are other modes, check the test project to see which one
serves you better.

**Comment by kitty8904** [comment]
<img width="764" alt="666" src="https://user-images.githubusercontent.com/18622105/70383388-8b495980-19b0-11ea-91f1-e718309c3777.png">

Test project compilation is no problem

I can't see the project on Lazarus instead.

Unable to find the component class "TBCDRadioButton"

**Comment by lainz** [comment]
Yes we know. By default custom drawn controls are not installed.

Open the bgracontrols lpk package with Lazarus and include on installation
the custom drawn files (checkbox register and use of I remember correctly).
Then rebuild Lazarus.

I'm not on a PC right now to tell you the exact filenames.

**Comment by kitty8904** [comment]
<img width="381" alt="777" src="https://user-images.githubusercontent.com/18622105/70383556-16c3ea00-19b3-11ea-9176-f609adc51f64.png">

okay register lazarus rebuild -> Without a problem, an additional checkbox now appears in Lazarus

thank you

**Comment by kitty8904** [comment]
<img width="230" alt="88" src="https://user-images.githubusercontent.com/18622105/70383832-2265df80-19b8-11ea-9947-592723283cd8.png">

Custom checkboxes have no event handlers instead

Will it be added later?

Images look better with custom checkboxes

**Comment by lainz** [comment]
I see. Custom Drawn checkbox inherits from custom drawn package that we
don't maintain. But yes it will be a good thing to add events.

What events do you need?

**Comment by kitty8904** [comment]
OnChange or OnClick

Or it would be nice if the Lazarus default checkbox event was applied

BGRA is a good tool

**Comment by lainz** [comment]
Thanks. Well I will see if I can add these. OnClick for sure. But to add
OnChange I need to modify Lazarus sources and send a bug report so Lazarus
dev's can add that to custom drawn package (that's part of Lazarus itself).

It will be easier to create a custom theme for bgrathemes checkbox that
looks like custom drawn checkbox. And there we are free to add any events
we want.

**Comment by lainz** [comment]
If creating a custom theme is hard... you can use already made color theme
from bgrathemes tab (check test project for usage). And use the same colors
as in custom drawn components to paint the checkbox.

Well if you have any other questions just open a new bug report or also
check the Lazarus forum I visit it regularly.
