### ISSUE TITLE
TBCComboBox anchors?

### ISSUE THREAD

**Issue by kitty8904** [bgrabitmap/bgracontrols#58]
<img width="652" alt="anch" src="https://user-images.githubusercontent.com/18622105/71629445-e33a4f80-2c40-11ea-9558-5f264c4ee4d9.png">

TBCComboBox  combobox anchors how fix?

TBCComboBox doesn't have Lazarus anchors alignment feature How to fix or update later?

**Comment by lainz** [comment]
I've added it on the dev branch. You can wait until I release a new version or just download the bccombobox file and replace where you have your copy.

Or just add this line into your file:
https://github.com/bgrabitmap/bgracontrols/blob/dev-bgracontrols/bccombobox.pas#L87

**Comment by lainz** [comment]
Don't forget to rebuild Lazarus when you change the file to see the new property in the Object Inspector.

**Comment by kitty8904** [comment]
<img width="326" alt="eee" src="https://user-images.githubusercontent.com/18622105/71633009-0a9b1780-2c55-11ea-9234-abd0e4b5b353.png">

thank you!

and bgra tlistview add?

<img width="232" alt="eee2" src="https://user-images.githubusercontent.com/18622105/71633084-7b423400-2c55-11ea-86ff-4da4476749a5.png">

Is there any plan to add bgraTlistview using columns?

**Comment by lainz** [comment]
Hi, is not planned, the latest control we did was the combobox, since then only patches to existing controls.

**Comment by kitty8904** [comment]
The combo box modification is fine

I was wondering if there was a bgra dedicated tlistview

bgra is very useful for Lazarus scalability

good software

**Comment by lainz** [comment]
Thanks.
At this moment we don't have a dedicated tlistview. And is not planned at the moment.
