### ISSUE TITLE
Question about RadialProgressBar

### ISSUE THREAD

**Issue by JacoFourie** [bgrabitmap/bgracontrols#59]
Hi. I love your controls. Thanks for all the hard work.
I would love to use the Radial Progress bar as a Guage. Is there a way to remove the % and have the real value and not change it to a value between 0 and 100?

**Comment by circular17** [comment]
I suppose it could be done an OnFormat event.

About the formatting I noticed that if the value is like 1/3, it will be a long string like 0.33333333333333%

**Comment by JacoFourie** [comment]
I found a way around it thanks.
