### ISSUE TITLE
Error on null selected cropped area

### ISSUE THREAD

**Issue by aron62br** [bgrabitmap/bgracontrols#61]
When I select a null cropped area, by only click and release mouse button on image (no drag it), there is an error.

... exception 'External SIGSEGV'
... on file 'braimagemanipulation.pas' line 2552;
if (rSelectedCropArea.Area.Left > rSelectedCropArea.Area.Right) then

I think that the problem is some lines earlier.

at line 2544..
begin
      // Ends a new selection of cropping area
      if (rNewCropArea <> Nil) then
      begin
        rSelectedCropArea :=rNewCropArea;
        rNewCropArea :=Nil;
      end;

      if (rSelectedCropArea.Area.Left > rSelectedCropArea.Area.Right) then
      begin
        // Swap left and right coordinates
        temp := rSelectedCropArea.Area.Left;
        rSelectedCropArea.Area.Left := rSelectedCropArea.Area.Right;
        rSelectedCropArea.Area.Right := temp;
      end;       

Ok, If rNewCropArea is not null the code knows the how to deal, but, If the rNewCropArea IS null, the code does the same, then there are not iniciallized values...

Thanks

**Comment by lainz** [comment]
Ok thanks for reporting, did you found a way to fix it?

**Comment by lainz** [comment]
Fixed, I put the code inside the part 

`if (rNewCropArea <> Nil) then`

So it doesn't generate an exception when there is no crop area.
