### ISSUE TITLE
Edit Control

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#63]
Like TEdit with properties to theme it.

**Comment by Alexey-T** [comment]
You can use https://github.com/alexey-t/atSynedit in your package maybe.

**Comment by lainz** [comment]
Hi, that looks really advanced. It can be used like a normal edit control in some way?

**Comment by Alexey-T** [comment]
Yes, it has TATEdit which is one-line version (child) of TATSynEdit.

**Comment by lainz** [comment]
Ok thanks. For sure having that control into account, we only need to implement the painting (like rounded borders and gradient fill for example).

**Comment by circular17** [comment]
So I suppose there is a drawer that can be customized?

How does it handle complex unicode stuff, like non spacing markers, right-to-left script and embedding?

**Comment by lainz** [comment]
I'm not sure if theming a full syntax highlighter will be a good idea, since anyways modern code editors doesn't use gradients and rounded borders, it's always plain colors.

But yes it will be good to make an edit control, and if we can do 2 different ones will be good too, one with synedit and other with bcstylecustomcontrol to have more options, doesn't matter having 2 different controls, anyways we have a lot of button controls to choose from, and every single one is useful for something.

**Comment by lainz** [comment]
Attached a project that uses a TBCPanel and a TEdit.
[EditControl.zip](https://github.com/bgrabitmap/bgracontrols/files/5226380/EditControl.zip)

You can use a plain color for the background of the TEdit and of the TBCPanel.
![bgraedit](https://user-images.githubusercontent.com/4131395/93237788-f94c5980-f756-11ea-809c-708949580790.png)

That is how it looks under Windows. How it looks under Linux and macOS, please test, and if it looks ok we can make a simple component including that template, like we did for BCCombobox that's just a button and a listbox 👍

**Comment by lainz** [comment]
Hi, anyone tested it, looks good on Linux and macOS?

**Comment by circular17** [comment]
It works on MacOS. Though the cursor is black so can't really see it on the dark background.

**Comment by lainz** [comment]
Ok, so it doesn't work well on all platforms..

**Comment by circular17** [comment]
Yeah but it is more like a bug of TEdit with custom background color

**Comment by lainz** [comment]
Ok, it worth reporting it in the bugtracker, so it can be fixed, can you add some screenshot so I can share there?

**Comment by circular17** [comment]
Reported: https://bugs.freepascal.org/view.php?id=38033

**Comment by lainz** [comment]
Thanks =)

**Comment by lainz** [comment]
Hope the bug is fixed soon. I think we don't need an edit, just using a BCPanel as border and a regular edit looks fine for me:
![Captura de pantalla 2020-11-28 224409](https://user-images.githubusercontent.com/4131395/100529976-4fb02c80-31cb-11eb-98cb-450ddcc706d7.png)

So I close this, if at some time we need it for some other reason, we can try coding that.
