### ISSUE TITLE
BGRAControls and MSEgui?

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgracontrols#67]
Hello!

Now that `BGRABitmap` is `MSEgui` compatible, do you think `that BGRAControls` could work for `MSEgui` too?

Thanks.

Fre;D

**Comment by lainz** [comment]
Hi, BGRAControls uses the LCL. How is called the widgetset in MSEgui?

Do you have an example of a custom control made with MSEgui that we can use as reference? With events like onEnter, onLeave, onClick...

**Comment by fredvs** [comment]
Hello.

> How is called the widgetset in MSEgui?

The widgetset is called, imho,  MSEgui...

> Do you have an example of a custom control made with MSEgui that we can use as reference?

MSEgui can use "template" for each of his widgets.
For example in [IdeU](https://github.com/fredvs/ideU) or [StrumPract](https://github.com/fredvs/strumpract) do use template for buttons, checkbox, etc...

![Sans titre](https://user-images.githubusercontent.com/3421249/80918018-04cc5480-8d63-11ea-9d64-4562c35faec2.png)

I realize now that in fact, just publishing some custom template could do the trick.
In other hand, tuning msegui template is not evident and "templates" out-of-the box, with look like your BGRAControls widgets will be highly appreciated.

Fre;D

**Comment by fredvs** [comment]
> How is called the widgetset in MSEgui?

Re-hello.

Hum, good question, I will ask it to MSE forum.

**Comment by lainz** [comment]
Ok. So if I understand it well is like a theme for the entire application?

**Comment by fredvs** [comment]
Each component is totally configurable.
For example a TButton has a frame property where you can assign the layout, the corners, etc of the frame.
The same for the face property, with background, the image, etc, all with parameters.

You may tune individually each component or use a "template" for each propery (frame, face, container, scroll, etc...) of the component.

That template of properties can be used by other components too.

It is a kind of theme for each property, and in the theme you may also have methods, like onpaint, onclick, etc...

So, for example you may have a `frame` template with round corners that you may use for your buttons, edit, grid, panels, etc, ...

And a `face` template with a shaded background, with a image grayed, etc that you may use for different components.

And this for nearly all property of the components.

By default, it has the look of old Windows 311 but all is customizable.

And the few examples of "style" that are in mseuniverse are not really, imho, much better than the default.

I agree it is not easy to understand how msegui works but at the end, when you get it,  you may do-custom all what you want.


.

**Comment by fredvs** [comment]
> Ok. So if I understand it well is like a theme for the entire application?

A `property template` is a widget, that you can use for the entire application, or only some part of the application and also for other applications.

I use 3 frame templates and some more `face templates` for nearly all my msegui apps.

**Comment by lainz** [comment]
I'm not sure where to start. For example I drop a paintbox and I want to draw with BGRABitmap on it, how I can do it? I already have cloned the repository of BGRABitmap somewhere in my disk, how I can add it to the MSEide project?

The idea I have is to provide you a simple class that can draw UI elements, like buttons, checkboxes, radiobuttons, and if you can help me put that in the code that is used to really draw them inside the controls. What do you think?

We can start with the button that's one is simple to do.

**Comment by fredvs** [comment]
> For example I drop a paintbox and I want to draw with BGRABitmap on it, how I can do it?

In the BGRABitmap issue bgrabitmap/bgrabitmap/#79 Roland and Circular have done some demos.

https://github.com/bgrabitmap/bgrabitmap/issues/79#issuecomment-614699414
https://github.com/bgrabitmap/bgrabitmap/issues/79#issuecomment-616626895

> The idea I have is to provide you a simple class that can draw UI elements, like buttons, >checkboxes, radiobuttons

Yes good idea (even if I dont see clearly at the moment how to do).

>  if you can help me put that in the code that is used to really draw them inside the controls. 

With great pleasure with what I know (but maybe with the help for some part msegui from people of msegui mailing list).

**Comment by fredvs** [comment]
IMHO, thez most complicated to catch is how to deal with the frame of widget.
For example how to do rounded or custom shape widget, in ideU or Strumpract it has rounded widgets.

But at the end, once you have done one, it works the same way for all widgets.

**Comment by lainz** [comment]
Thanks, I will check the demos and see what I can do.

**Comment by lainz** [comment]
Hi fred. I didn't have time to touch any code.
But better than that, I think I have a solution to make controls for fpgui, msegui and LCL. I write the main idea here.

Currently Bgrabitmap is the base layer, then we draw with it in the lcl or msegui duplicating code to draw.

My idea is to create another layer say bgraui that is responsible only to draw the complex stuff. You pass it variables and it draws for example the face of a button, with custom properties like the actual  TBCButton, but separate from the logic. With this new layer we can reuse the drawing of controls with bgracontrols for lcl and msegui and possibly fpgui as well, and any other target say probably android or opengl too.

So it must be like bgrabitmap but for drawing ui. Not included the control logic, that's left for each widget say lcl or msegui.

All the properties can be shared as well contained into a single bgraproperties that can be shared between lcl and msegui. Like a single object with all the sub properties. For example now we have " state normal - background  - color " and " rounding" properties.  We can grab all of them and put in a single object in a single property like bgrastyle that can have all style related stuff. So we can put that single property in the lcl and msegui,  link that with the bgraui drawer and forget.

The events can be set inside that bgrastyle and passed directly to the bgraui drawer. So we can have some logic too.

So the final responsibility on the lcl and msegui will be only changing the state of the bgrastyle property and pass it to the bgraui drawer.

Bgrastyle and bgraui are the names that I created just now to differentiate the library name and the property name. But can be named anything else.

I discard the idea of what I did in bgrathemes that the properties are stored in a theme component since people find more easy to have the style in the same instance of the control instead into a separate component. 

Finally all bgracontrols must be done from scratch to support this new way of coding. But the real advantage is that we can support lcl, msegui, fpgui and probably android and opengl. We can also make some html and css output as well if we find the way.

Seems a bit complicated but is really easy, just a new layer.

**Comment by lainz** [comment]
@circular17 what do you think?

**Comment by lainz** [comment]
I found some confusion in what I said. First the logic. The logic is in the lcl or msegui. Changing the events on mouse enter and mouse leave, click, and so on. The state in the property bgrastyle is changed and then the control is drawn with bgraui drawer, say in this case bgrauibuttondrawer. But it just draws the state passed by the control, the responsibility at the end is to draw given a state. That state is changed according to the events in lcl for example.

**Comment by lainz** [comment]
Anyway the controls must be done from scratch to work for msegui. So it will be a new package not touching the already working bgracontrols that's widely used.

**Comment by circular17** [comment]
Yeah it is good idea to do different layers. As you say on one hand, the UI system is different, and on the other, the drawing can be the same.

**Comment by fredvs** [comment]
Hello Leandro.

Many thanks to take care about msegui.
Yes, using layer seems a excellent idea.

I will jump into msegui code to see how to create new components.
Write you later.

Fre;D

**Comment by fredvs** [comment]
Here some info from msegui readme;txt:

How to add custom components to MSEide
**************************************
There is a project 'apps/myide/mymseide.prj' as a demo.
Start MSEide, open project 'apps/myide/mymseide.prj', 'Project'-'Build',
'Target'-'Continue',
the IDE with the new component 'tmybutton' will be compiled and
started in the the debugger.
Binary name is 'mymseide' (linux) or 'mymseide.exe' (win32).

If you wish to do it from scratch:

- Create a register unit for your components 
  (see 'apps/myide/regmycomps.pas' for an example).
- Enter the unitname followed by a comma 
  ('myregunit,' if your regunitfile is 'myregunit.pas') in 
  a file named 'regcomponents.inc'.
- Build the IDE with -dmorecomponents as option.

If you want add custom icons to your components:

- Convert 24*24 pixel BMP or PNG files with tools/bmp2pas to
  an icon unit ('*_bmp.pas').
- Add the name of the icon unit to 'uses' in your register unit.

**Comment by lainz** [comment]
Thanks @circular17 and @fredvs.

**Comment by lainz** [comment]
Hi, I've created the repository bgragui, added an LCL button control and a drawer that currently just draws the background color and the caption to test (in the dev-bgragui branch). Next will be creating the control in msegui, but today I need to do other things, so I will continue the next weekend.

If you want to try install both packages, bgragui and bgraguicontrols, only for lazarus right now. Next weekend is time for msegui.

**Comment by fredvs** [comment]
Hello Leandro.

Excellent.

If you need some help for msegui or fpgui, please say it.

Fre;D

**Comment by fredvs** [comment]
For fpgui, I can adapt first [uidesigner_ext](https://github.com/fredvs/uidesigner_ext/).
And when all is ok, we can do a pull_request for official Graeme's fpgui uidesigner.

Fre;D

**Comment by lainz** [comment]
Hi Fred, I compiled 'my ide' project and I can't find the mybutton component, you know where it should be? Like in which tab?

**Comment by fredvs** [comment]
Hola Leandro.

OK, I will jump tonight into the code, (I never try it).
Write you later.

**Comment by fredvs** [comment]
OK, done.
When the compilation is done, run the application.
Then, load the `Component Palette`, with menu `View`

![Sans titre2](https://user-images.githubusercontent.com/3421249/81508879-1d121580-9307-11ea-987d-35101a783147.png)

The new button is in the last right tab:

![Sans titre](https://user-images.githubusercontent.com/3421249/81508915-4cc11d80-9307-11ea-992d-bee2a021e594.png)

**Comment by fredvs** [comment]
Hum, I never try it but, one more time, i am totally impressed by msegui.
Here it compiled out-of-the-box, the new button is working and integrated into the` Component Palette` form.

**Comment by lainz** [comment]
Thanks, I found it. But when I try to use mybutton FPC can't find it: 'Can't find mybutton used by main' in a new project..

**Comment by lainz** [comment]
But the control is drawn, I can see the green drawing, because I've added the BGButtonDrawer, that draws a green background. At least that works!

**Comment by lainz** [comment]
```
unit mybutton;
{$ifdef FPC}{$mode objfpc}{$h+}{$endif}

interface
uses
 msesimplewidgets,mseevent,msegraphics,classes,mclasses,msegraphutils,mseact,
 mseguiglob, bgrabitmap, bgrabitmaptypes, bgbuttondrawer;

const
 defaultcolorclicked = cl_red;

type
 tmybutton = class(tbutton)
  private
    fbgra: TBGRABitmap;
    FStyle: TBGButtonDrawer;
  protected
   procedure paint(const canvas: tcanvas); override;
  public
    constructor create(aowner: tcomponent); override;
    destructor destroy; override;
  published
    property Style: TBGButtonDrawer read FStyle write FStyle;
 end;

implementation
uses
 mseshapes;

{ tmybutton }

constructor tmybutton.create(aowner: tcomponent);
begin
  fbgra := TBGRABitmap.Create(width, height);
  fstyle := TBGButtonDrawer.Create;
  inherited;
end;

destructor tmybutton.destroy;
begin
  fbgra.Free;
  fstyle.Free;
  inherited;
end;

procedure tmybutton.paint(const canvas: tcanvas);
begin
  if (Width <> FBGRA.Width) or (Height <> FBGRA.Height) then
    FBGRA.SetSize(Width, Height);
  fstyle.Draw(fbgra);
  fbgra.Draw(canvas, 0, 0);
end;

end.

```

**Comment by fredvs** [comment]
> But when I try to use mybutton FPC can't find it: 'Can't find But when I try to use mybutton FPC can't find it: 'Can't find mybutton used by main' in a new project.. used by main' in a new project..

Maybe copy your mybutton into the directory of msegui, for example create a directory `/mseide-msegui/lib/common/BGRAcomponents`  and paste all your units there, it will be in the search list.

How did you do to test your button, did you create a new project, then adding the button from the component palette?

**Comment by lainz** [comment]
> How did you do to test your button, did you create a new project, then adding the button from the component palette?

Yes, I had an existing project, then added the button from the palette, the unit is added in the uses clause, but can't find it.

I will try to create a custom register for units, so I can place them in common folder.

**Comment by fredvs** [comment]
Indeed, compile it without copy your unit into msegui/lib/common/ I get:

![Sans titre](https://user-images.githubusercontent.com/3421249/81510303-040e6200-9311-11ea-8d75-c228932fda6e.png)

But if you copy the files in /mseide-msegui/lib/common/BGRAcomponents

![Capture d’écran_2020-05-10_22-52-25](https://user-images.githubusercontent.com/3421249/81510322-20aa9a00-9311-11ea-9f84-17aef98c1d65.png)

The test compiles and run here.

![Sans titre3](https://user-images.githubusercontent.com/3421249/81510389-99a9f180-9311-11ea-9fca-a25cef2420bd.png)

**Comment by fredvs** [comment]
Ha, ooops, I did not see your previous post, you are already into BGRAbitmap.

Wow.

OK, I will try your code.

**Comment by fredvs** [comment]
Sorry but I have problem here to compile your code.
There is that error message, where can I find that unit `AvgLvlTree`?

`bgrapalette.pas(8,22) Fatal: Can't find unit AvgLvlTree used by BGRAPalette`

**Comment by lainz** [comment]
I don't know, I'm using fpc trunk, maybe circular knows where to find it.

**Comment by lainz** [comment]
Thanks, my code isn't doing too much, just drawing a green rectangle now. Next weekend I will try to add the events.

**Comment by fredvs** [comment]
OK, found, it is a Lazarus component:

/lazarus/2.0.6/components/lazutils/avglvltree.pas(16,6): unit AvgLvlTree;

I tune everything and write you later.

**Comment by fredvs** [comment]
Hum, ok for AvgLvlTree but for this one... ?

`mybutton.pas(7,43) Fatal: Can't find unit bgbuttondrawer used by mybutton`

**Comment by fredvs** [comment]
> Next weekend I will try to add the events.

OK, perfect, read you next week.

Gracias.

Fre;D

**Comment by lainz** [comment]
> Hum, ok for AvgLvlTree but for this one... ?
> 
> `mybutton.pas(7,43) Fatal: Can't find unit bgbuttondrawer used by mybutton`

That unit is on the bgragui repository, in the dev branch

**Comment by fredvs** [comment]
> That unit is on the bgragui repository, in the dev branch

Ha, very excellent idea, (but dont forget to add also the dependencies of that units).

**Comment by lainz** [comment]
Installed in the BGRAGUI Controls pallete.

Instructions on how to install BGRAGUI in MSEIDE
https://github.com/bgrabitmap/bgragui/tree/dev-bgragui#mseide-instructions

This I get so far:
![msegui](https://user-images.githubusercontent.com/4131395/81514122-9d367c00-9303-11ea-81c5-9fe999665676.png)

No events yet. That's all for today, events as I said for next week.
