### ISSUE TITLE
License headers

### ISSUE THREAD

**Issue by circular17** [bgrabitmap/bgracontrols#69]
To be able to include files in a Debian package, it is recommended that each file would have a header specifying the license, and that the full text of the license be provided as a separate file. This would probably be required if we hope adding our applications to Debian distributions.

In the case of opensource Lazarus packages, it is the modified LGPL license.

So in each code file, except bgracontrols.pas which is generated, I suggest to add:
`// SPDX-License-Identifier: LGPL-3.0-only (modified to allow linking)`
That's more or less the syntax used in Inkscape code files. Note that the `(modified to allow linking)` text is not part of this protocol, but would probably be ignored by an automatic parser. Anyway, the modified linking is only relevant for Lazarus when we link libraries.

And in the base directory, add the files COPYING.LGPL.txt and COPYING.modifiedLGPL.txt.
[COPYING.LGPL.txt](https://github.com/bgrabitmap/bgracontrols/files/4651808/COPYING.LGPL.txt)
[COPYING.modifiedLGPL.txt](https://github.com/bgrabitmap/bgracontrols/files/4651809/COPYING.modifiedLGPL.txt)

I can do the change though I would like to have another opinion about it.

**Comment by lainz** [comment]
I think it's ok. Do the change for all required units and packages.

**Comment by lainz** [comment]
As well if you have time please remove any comments that are in the top part of the files like change logs or credits. We have the readme file for that purpose: there I listed all the credits for each unit but seems that's its outdated now.

**Comment by circular17** [comment]
Ok.

**Comment by circular17** [comment]
I am not sure about the changes and credits. I prefer to let you do that.

I will tell you when I am finished with the licensing.

**Comment by circular17** [comment]
Done on dev branch.

I let you check for the other information in the file headers.

**Comment by lainz** [comment]
Ok no problem.  When you're done just publish it on the master branch. If a new release is needed we can just increase the build number.

**Comment by circular17** [comment]
Ok done merging.

**Comment by circular17** [comment]
Note that I may do other changes so don't rush to publish

**Comment by lainz** [comment]
Ok.

**Comment by lainz** [comment]
I published since I did a bugfix for the ComboBox.

**Comment by circular17** [comment]
Yep that's alright.

**Comment by lainz** [comment]
Is this done @circular17 ?

**Comment by circular17** [comment]
Yes. Sorry I forgot about it.

**Comment by lainz** [comment]
I've added a new component, but not added the license, I will add it.
