### ISSUE TITLE
add ATShapeLine

### ISSUE THREAD

**Issue by Reaper10** [bgrabitmap/bgracontrols#71]
add ATShapeLine to bgrabitmap.  It mite be good to be able to leave of the arrow.
https://github.com/Alexey-T/ATShapeLine
https://wiki.freepascal.org/ATShapeLine

**Comment by circular17** [comment]
Hmm, the simplest way would be to use TBGRABitmap.Canvas2D in the Paint method. For example in a temporary TBGRABitmap.

**Comment by lainz** [comment]
Hi, on dev branch I've added TShapeLineBGRA, as circular said changing Canvas with CanvasBGRA.
https://github.com/bgrabitmap/bgracontrols/blob/dev-bgracontrols/atshapelinebgra.pas
