### ISSUE TITLE
Possible bug in TBCComboBox

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#73]
Tested today in a form that's show modal, the combobox is used inside that form, the modal is closed. The form is not released. Then the form is used again. On Linux and Mac it fails, it doesn't display the dropdown listbox again.

I think is a problem with ShowModal on these OS. I'm using FPC trunk and Lazarus trunk. That can be part of the problem too.

I add it here to test later.

**Comment by circular17** [comment]
Ok.

**Comment by lainz** [comment]
The added timer code is maybe related to this bug? Like to close the dropdown?

**Comment by circular17** [comment]
I've just updated the code. This may have fixed the problem.

**Comment by circular17** [comment]
I've added the timer code because on MacOS the Deactivate event does not seem to happen, so that checks if the form gets deactivated.

**Comment by lainz** [comment]
Ok yes I think that solves the problem.

**Comment by circular17** [comment]
Cool. So issue is closed?

**Comment by lainz** [comment]
Yes solved thanks.
