### ISSUE TITLE
TBCComboBox focus and tabstop

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#74]
Hi, we can implement focusing and tabstop for TBCComboBox, it will cause any problems in LazPaint?

It will be like this:
- Changing to TBCButtonFocus
- Drawing a FocusRect in the redraw event
- Providing a color property for the FocusRect
- Adding keyboard handling like when pressing the enter key opens the list
- Pressing the enter key in the list selects and closes the list

**Comment by lainz** [comment]
@circular17 what do you think?

**Comment by lainz** [comment]
I think better to have a separate control with focus, because we will lose transparency if we use TBCButtonFocus.

Say I can copy the sources and replace TBCButton with TBCButtonFocus, so the existing comboboxes keep working in the same way.

**Comment by circular17** [comment]
Indeed, the background may be an issue. If you would do it anyway, I guess for LazPaint and also other prorgams, what matters is that the TabStop would be False by default, to make it compatible.

**Comment by lainz** [comment]
Ok I've done the changes, with enter key you access the items, with enter key as well closes the list. I've added focus border color property as well.

I've done a thing a bit hacky, the redrawing of the button changing the caption and bringing it back to it's original caption to force the redraw... Maybe we can make public the redraw event of the button?

I've merged the changes since I need to test in an environment that uses OPM.

The combobox was already a TControl, so I've keep the TBCButton without focus, and added the focusing code in the combobox, and using the redraw event for the button.

**Comment by lainz** [comment]
If you have some time please test it and if all is ok we can do the release.

**Comment by lainz** [comment]
ToDo:
cuando tiene foco del teclado no cambia con las flechas o las letras
si se despliega con enter, ahi si se puede cambiar con las flechas
pero si le das esc cierra el frmcobrar pero queda el form q simula el combobox

**Comment by lainz** [comment]
Let's see if I can finish the changes this Sunday.

**Comment by circular17** [comment]
Sorry I think I did not get back to you about this one. I am not sure to understand. Going to try a bit and see.

**Comment by circular17** [comment]
I don't see any difference on MacOS. Do you have a screenshot of how it is supposed to look like?

**Comment by lainz** [comment]
When TabStop property is true and you set the focus color it looks like this:

![bccombobox](https://user-images.githubusercontent.com/4131395/85201750-39c34500-b2d8-11ea-96a9-7346e5289f5a.png)

What is missing is the keyboard, pressing keys up and down to navigate elements when is focused and pressing the normal keys to navigate as well, for example if I press 'a' then navigate to element that contains an 'a' at the beginning. I'm trying to do that tomorrow.

**Comment by lainz** [comment]
I've implemented keyboard with up and down keys and also regular keys to navigate. Also esc closes the list box form.

If everything is ok in linux and mac we can close this bug report I think.
