### ISSUE TITLE
macOS retina for BGRAControls

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#78]
Like @circular17 explained here
https://forum.lazarus.freepascal.org/index.php/topic,33215.msg365850.html#msg365850

I think also line width (border of button for example) must be scaled, 1px to 2px and so on. And maybe we can scale as well Windows 10 controls line width when using High DPI at 200% resolution.

**Comment by circular17** [comment]
Indeed, borders are to be scaled and also fonts.

**Comment by lainz** [comment]
Do you still have access to that retina mac?

And is just scaling the units enough, no need to worry about anything else except for the final drawing to canvas?

**Comment by circular17** [comment]
Yes.

It is indeed rather straightforward. Draw everything twice as big. Note that for mouse events you need to adjust the coordinates for example, if you have stored the clicked area scaled.

**Comment by lainz** [comment]
Ok.

**Comment by lainz** [comment]
So almost everything is retina, cool =)

**Comment by circular17** [comment]
Hmmm let's summarize.

Retina support: BCButton (except glyph), BCComboBox, BCSVGViewer, BCSVGButton, BCTrackbarUpDown, BGRAGraphicControl, BGRAShape, BGRAVirtualScreen

I guess if someone need one more, we can do that at this point.

Maybe doing PCPanel would be like a basic one to do.

**Comment by lainz** [comment]
I think we can fix the retina stuff for the glyph, getting the right image size for the BCButton.

**Comment by circular17** [comment]
Well for now the image is stretched. For backward compatibility, I think we need a new property. Either something like a zoom ratio / scaling mode / glyph size, so that we can provide an image with more pixels as Glyph but that would be drawn at the right proportion, or another Glyph property to hold the image with Retina definition.

**Comment by circular17** [comment]
I imagine something like this:
- add a RetinaGlyph property, that will be drawn at 50% of its size (on Retina that will be the actual resolution)
- when drawing, prefer Glyph property for regular display and prefer RetinaGlyph for Retina
- one can provide only RetinaGlyph or only Glyph, and it will be stretched if needed

For most glyph, one could just supply the RetinaGlyph. The scaling would be fine if the positions are at even coordinates (0, 2, 4, etc.)

Though that doesn't cover high DPI. Maybe be can add GlyphZoom property as well. If we set it to 2, then that would use the RetinaGlyph at its actual size on non Retina display. Though if DPI is 150%, i.e a zoom factor or 1.5, the stretched icons may not look perfect.

**Comment by lainz** [comment]
What I think about is using the High DPI / retina image list. There are already an imagelist and imageindex properties. Just that is not grabbing the right resolution from the imagelist.

I think with that we can keep the code like actually is, don't touching the glyph property, and if someone wants high resolution can use already the high resolution imagelist =)

**Comment by circular17** [comment]
Yeah we can keep things simple like that. Maybe we could just add a GlyphAutoscale property (by default True), so that one can disable it on Retina and provide the full-resolution glyph. That would be simple enough and still allow to use the accurate resolution.

**Comment by lainz** [comment]
Good, yes that sounds good, I will try on weekend to implement the imagelist code, and I let you the glyph since I don't have retina display to test.

**Comment by lainz** [comment]
I did the changes for bcbutton imagelist.

Basically if you have selected an image list as icon source for BCButton, it works the same as before, but if in the image list you turn on the scaling property, it gets the bigger images if the DPI is bigger. It should work as well on macOS.

Here a simple test project, base icon size is 16x16, I've added resolutions for 125%, 150%, 175% and 200%. The AutoSize property  works as well.

[test bcbutton imagelist.zip](https://github.com/bgrabitmap/bgracontrols/files/5498551/test.bcbutton.imagelist.zip)

If it doesn't found the resolution based on dpi and scale factor, I've seen that it draws the next smaller. So it works fine if you provide the resolutions, and since is an opt-in feature is backward compatible.

**Comment by circular17** [comment]
Hi, thanks for the test project.

Well, the Retina part doesn't work. That's because the size is computed mostly ignoring Retina scaling. And then when rendering the glyph, the scaling must be set to 1 if the bitmap form the image list is upscaled.

I've fixed that, and also added code to compute the font size using Retina scaling. By the way the default size of 0 needed to be actually determined before scaling.

In the end, I've added a GlyphScale property. When set to 1, the glyph is drawn as before. One can set to 0.5 to draw it twice as small and provide a higher resolution image for Retina. Or one can set it to DPI/96 to apply a crude scaling. So for example, if you apply a style to a BCButton, you can scale it according to DPI as you would with other parameters.

**Comment by lainz** [comment]
Thanks for fixing it =)

**Comment by circular17** [comment]
Here is a test using it. I've also added ScaleStyle function to BCButton. In this case, it scales just the text margin, but it can scale everything.
[bcimglist-glyphscale.zip](https://github.com/bgrabitmap/bgracontrols/files/5501229/bcimglist-glyphscale.zip)

**Comment by lainz** [comment]
Sorry for the delay. It looks good in the image. I think everything should be scaled, all that's possible to scale, because is like zooming, so for me it's fine.

**Comment by circular17** [comment]
Ok

**Comment by lainz** [comment]
Thanks for all the controls with retina, I think is enough with them, the new SVG controls can replace many and these are already retina (button, image list) so I close this.
