### ISSUE TITLE
Fresh install fails on fresh install of Lazarus 2.0.10

### ISSUE THREAD

**Issue by BobanSpasic** [bgrabitmap/bgracontrols#79]
Compiling fails with the message:
bcimagebutton.pas(30,32) Fatal: Cannot find BGRASliceScaling used by BCImageButton, incompatible ppu=C:\Users\...\packages\bgrabitmap-11.1\bgrabitmap\lib\x86_64-win64\3.2.0\bgraslicescaling.ppu, package BGRABitmapPack

**Comment by lainz** [comment]
Hi, that message is happening in any version of Lazarus and FPC, we don't know why, but is a problem with FPC and not of the packages.

**Comment by BobanSpasic** [comment]
Is there any way to complete the installation?

**Comment by lainz** [comment]
I usually do a 'Clean up and build lazarus' and I select 'clean common files' from the build lazarus menu.
