### ISSUE TITLE
Add GroupIndex in Buttons Controls

### ISSUE THREAD

**Issue by salvadorbs** [bgrabitmap/bgracontrols#80]
I'm porting my software from Delphi to Lazarus and considering that CindyComps in Lazarus has poor performance and issues, I want using BGRA Controls. Precisely I'm using TBCImageButton, but I miss a property like GroupIndex. With this property, I can use TBCImageButton as tab controls. So I have only one button in pressed state and others "up" state.

**Comment by lainz** [comment]
Hi, you should create a new class like TMyBCImageButton = class(TBCImageButton) and add these custom properties there. Or using class helpers as well, but I've not used these too much so maybe ask in the forum if you don't know how to use them.

**Comment by salvadorbs** [comment]
No problem. I will extend TBCImageButton in my Application. Thank you anyway!
