### ISSUE TITLE
BGRAControls and MSEgui

### ISSUE THREAD

**Issue by fredvs** [bgrabitmap/bgracontrols#86]
Hello.

I am trying to convert some BGRABitmap demos using MSEgui widgetset.
Now I am busy with the "fractal_tree" demo.

But it fails to compile with that error:

`bgravirtualscreen.pas(48,34) Fatal: Can't find unit LMessages used by BGRAVirtualScreen`

Is it possible to use BGRAControls without the LCL LMessages unit (and all other LCL dependencies like graphtypes) ?

Thanks.

Fre;D

**Comment by fredvs** [comment]
Re-hello.

I did not catch the advantage of bgravirtualscreen, is it possible to draw on a canvas of a maximized from without bgravirtualscreen?

Thanks for some light.

Fre;D

**Comment by fredvs** [comment]
Re-re hello.

Ok,  the convertion of "Fractal Tree"  BGRABitmap demos using MSEgui widgetset is ok.

By the way, big WoW.

But this without using bgravirtualscreen, so I dont know if it is the good way and if there will be problems.

![Capture d’écran_2020-08-18_23-57-15](https://user-images.githubusercontent.com/3421249/90570050-44526b80-e1af-11ea-9db4-959681c5a1cc.png)

**Comment by lainz** [comment]
It will be good without bgravirtualscreen. Looking good.

**Comment by fredvs** [comment]
Hello.

Here a Dancing Fractal Tree:

[image_dancer.mp4.zip](https://github.com/bgrabitmap/bgracontrols/files/5093744/image_dancer.mp4.zip)

**Comment by circular17** [comment]
BGRAVirtualScreen can provide some optimizations but if it works well with a TMSEPaintBox, that's quite good. In particular if you refresh the whole area anyway.

**Comment by fredvs** [comment]
Ha ok, thanks.
By the way, I dont use a TMSEPaintBox anymore but directly the canvas of a TMSEform and the result is perfect.
(And faster than the same demo done with a TLCLform, but, ok, ok, no propaganda.)
