### ISSUE TITLE
Check this components

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#87]
https://github.com/Onur2x/onurcomp/
It's using bgrabitmap as well.

**Comment by lainz** [comment]
I've seen that components and in my opinion they look a bit ugly, sorry, but at least they have some edit controls, maybe because it's public domain we can look at the sources.

I close this since it get no responses.

**Comment by circular17** [comment]
Sorry I did not know what to respond. I guess it would be better to provide screenshots. I will add such issue in the project.

**Comment by lainz** [comment]
No problem. I'm adding a screenshot, as you can see is not bad but it can be better. Looking a bit old in my opinion.
![onurcontrols](https://user-images.githubusercontent.com/4131395/94366193-cdad6580-00ac-11eb-85ba-9c3f6f5ad5cf.png)

**Comment by circular17** [comment]
Yeah I see. I wonder about the white pixels around OnGraphicButton.
