### ISSUE TITLE
LoadFromResource / AssignFromResource using BGRAResource

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#93]
Is needed to change in all places that has a function to load from resource.

https://forum.lazarus.freepascal.org/index.php/topic,52016.msg382766.html#msg382766

**Comment by lainz** [comment]
Done in SVGViewer, missing in BGRASpriteAnimation, not sure on how to do it...

**Comment by circular17** [comment]
done on dev

**Comment by lainz** [comment]
Thanks, it was the one missing, so I close this.
