### ISSUE TITLE
ThemeButton issue

### ISSUE THREAD

**Issue by lainz** [bgrabitmap/bgracontrols#95]
When you open a ShowMessage in the OnClick event the mouse over drawing keeps active in the button and it doesn't change until you move the mouse over the button again.

**Comment by lainz** [comment]
Fixed, using code from TBCGraphicButton.

**Comment by circular17** [comment]
Sorry but it did not work for me also it changed the state of the disabled button.

First I fixed the state update, then I've added some code to release the button. Does that work for you?

**Comment by lainz** [comment]
Hi it doesn't works in all cases, for example this one:

```
procedure TForm1.BGRAThemeButton1Click(Sender: TObject);
begin
  BGRAThemeButton1.Enabled := False;
  ShowMessage('ok?');
end;
```

It remains hovered when it must be disabled.

**Comment by lainz** [comment]
Maybe in other buttons there is the same bug (BCImageButton), since them has the same code I've used for this one... so it was not working on macOS?

**Comment by circular17** [comment]
Nope, was not working. I am sure it is easy to fix now the Enabled thing.

**Comment by lainz** [comment]
Yes for sure, I will try. Strange that one thing works in one OS and not in other =(

**Comment by circular17** [comment]
Well, I suppose the code was relying on an update of the control when the dialog shows up, but that is not guaranteed. Crossplatform interface is not easy, you need to know what you are doing.

**Comment by lainz** [comment]
I didn't understand fully the method anyways, just the one I did that was not working as well =)
Maybe BCButton and other has the same issue, since I used the same 'fix' for them.

**Comment by lainz** [comment]
Thanks, your code was easy to read and to implement the missing case. Fixed on dev.
