### ISSUE TITLE
Error instaling BRGAControls in Lazarus 2.1.0 com Windows 10

### ISSUE THREAD

**Issue by edsontmarques** [bgrabitmap/bgracontrols#97]
Compilar pacote bgracontrols 7.1: Código saída 1, Erros: 1, Dicas: 2
bgraspriteanimation.pas(430,13) Error: Can't determine which overloaded function to call
gencurr.inc(24,14) Hint: Found declaration: Trunc(Comp):Int64;
gencurr.inc(17,14) Hint: Found declaration: Trunc(Currency):Int64;

A Ctrl+left-mouse at the tunc call on BRGASpriteAnimation points to currh.inc (when in Windows 10) and mathh.inc when Linux.

**Comment by circular17** [comment]
I suppose it is in function TBGRASpriteAnimation.DoCalculateSize. The call to trunc un superfluous. You can remove it.
